name: buddi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  device_apps: ^2.0.2

  cupertino_icons: ^1.0.8

  # Firebase (compatible set)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.2
  cloud_firestore: ^5.4.4
  firebase_analytics: ^11.6.0

  flutter_local_notifications: ^17.0.0

  # Module 4 & 5 packages
  pedometer: ^4.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^0.69.0  
  url_launcher: ^6.3.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  intl: ^0.19.0
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: GoogleSansFlex
      fonts:
        - asset: assets/fonts/Google_Sans_Flex/GoogleSansFlex-VariableFont_GRAD,ROND,opsz,slnt,wdth,wght.ttf
